// <auto-generated />
using Formacao1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Site_v3_dinamico.Migrations
{
    [DbContext(typeof(FormacaoBdContext))]
    [Migration("20210118190518_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Site_v3_dinamico.Models.Formacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("conteudosCurso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dataIniciodataFim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomeCurso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomeInstituicao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Formacao");
                });
#pragma warning restore 612, 618
        }
    }
}
