// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Site_v3_dinamico.Data;

namespace Site_v3_dinamico.Migrations
{
    [DbContext(typeof(SiteDinamicoBdContext))]
    [Migration("20210124174907_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Site_v3_dinamico.Models.Competencias", b =>
                {
                    b.Property<int>("CompetenciasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("descricaoComp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("nivelComp")
                        .HasColumnType("int");

                    b.Property<string>("nomeComp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomeLinguagem")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompetenciasId");

                    b.ToTable("Competencias");
                });

            modelBuilder.Entity("Site_v3_dinamico.Models.Exp_profissional", b =>
                {
                    b.Property<int>("Exp_profissionalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("dataFim")
                        .HasColumnType("int");

                    b.Property<int>("dataInicio")
                        .HasColumnType("int");

                    b.Property<int>("descricaoFuncao")
                        .HasColumnType("int");

                    b.Property<int>("funcao")
                        .HasColumnType("int");

                    b.Property<string>("nomeEmpresa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Exp_profissionalId");

                    b.ToTable("Exp_profissional");
                });

            modelBuilder.Entity("Site_v3_dinamico.Models.Formacao", b =>
                {
                    b.Property<int>("FormacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("conteudos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dataIniciodataFim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomeCurso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomeInstituicao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FormacaoId");

                    b.ToTable("Formacao");
                });
#pragma warning restore 612, 618
        }
    }
}
